matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode10.3

language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; sudo apt-get install -y qt5-default libqt5opengl5-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install -v qt5 vtk; brew link qt5 --force ; fi
  - MY_LOCATION=`pwd`
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - MY_LOCATION=`pwd`
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - git clone https://github.com/quicky2000/quicky_exception.git
  - cd quicky_tools/setup
  - . setup.sh
  - cd $MY_LOCATION
  - chmod a+x repositories/quicky_tools/bin/*
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://www.vtk.org/files/release/9.0/VTK-9.0.1.tar.gz; tar -zxvf VTK-9.0.1.tar.gz; mkdir VTK-9.0.1_build; cd VTK-9.0.1_build; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_BUILD_TYPE:STRING=Release -DVTK_QT_VERSION:STRING=5 -DQT_QMAKE_EXECUTABLE:PATH=/usr/lib/qt5/bin/qmake -DCMAKE_PREFIX_PATH:PATH=/usr/lib/x86_64-linux-gnu/cmake -DBUILD_SHARED_LIBS:BOOL=ON -DVTK_MODULE_ENABLE_VTK_RenderingContextOpenGL2=YES ../VTK-9.0.1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j4; sudo make install; cd $MY_LOCATION; fi
  - mkdir build
  - cd build

script:
  - cmake $QUICKY_REPOSITORY/VTK_viewer
  - make
#EOF
